services:

  banco:
    image: postgres:18-alpine3.23
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/18/docker

  verdear:
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: banco
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: root
      DB_DATABASE: postgres
    depends_on:
      banco:
        condition: service_healthy
    ports:
      - '3000:3000'

volumes:
  pgdata:
